/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRecordsRouteImport } from './routes/admin/records'
import { Route as AdminPilotRouteImport } from './routes/admin/pilot'
import { Route as AdminBoundariesRouteImport } from './routes/admin/boundaries'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminApiRouteImport } from './routes/admin/api'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicOfflineRouteImport } from './routes/_public/offline'
import { Route as PublicMapRouteImport } from './routes/_public/map'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicGpsRouteImport } from './routes/_public/gps'
import { Route as PublicFeedbackRouteImport } from './routes/_public/feedback'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPilotRoute = AdminPilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoundariesRoute = AdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOfflineRoute = PublicOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMapRoute = PublicMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGpsRoute = PublicGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeedbackRoute = PublicFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/feedback': typeof PublicFeedbackRoute
  '/gps': typeof PublicGpsRoute
  '/login': typeof PublicLoginRoute
  '/map': typeof PublicMapRoute
  '/offline': typeof PublicOfflineRoute
  '/search': typeof PublicSearchRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/boundaries': typeof AdminBoundariesRoute
  '/admin/pilot': typeof AdminPilotRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/feedback': typeof PublicFeedbackRoute
  '/gps': typeof PublicGpsRoute
  '/login': typeof PublicLoginRoute
  '/map': typeof PublicMapRoute
  '/offline': typeof PublicOfflineRoute
  '/search': typeof PublicSearchRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/boundaries': typeof AdminBoundariesRoute
  '/admin/pilot': typeof AdminPilotRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/feedback': typeof PublicFeedbackRoute
  '/_public/gps': typeof PublicGpsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/map': typeof PublicMapRoute
  '/_public/offline': typeof PublicOfflineRoute
  '/_public/search': typeof PublicSearchRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/boundaries': typeof AdminBoundariesRoute
  '/admin/pilot': typeof AdminPilotRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feedback'
    | '/gps'
    | '/login'
    | '/map'
    | '/offline'
    | '/search'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/pilot'
    | '/admin/records'
    | '/admin/reports'
    | '/admin/upload'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/feedback'
    | '/gps'
    | '/login'
    | '/map'
    | '/offline'
    | '/search'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/pilot'
    | '/admin/records'
    | '/admin/reports'
    | '/admin/upload'
    | '/admin/users'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/feedback'
    | '/_public/gps'
    | '/_public/login'
    | '/_public/map'
    | '/_public/offline'
    | '/_public/search'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/pilot'
    | '/admin/records'
    | '/admin/reports'
    | '/admin/upload'
    | '/admin/users'
    | '/_public/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pilot': {
      id: '/admin/pilot'
      path: '/pilot'
      fullPath: '/admin/pilot'
      preLoaderRoute: typeof AdminPilotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/boundaries': {
      id: '/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AdminBoundariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/offline': {
      id: '/_public/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof PublicOfflineRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/map': {
      id: '/_public/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof PublicMapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gps': {
      id: '/_public/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof PublicGpsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/feedback': {
      id: '/_public/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof PublicFeedbackRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicFeedbackRoute: typeof PublicFeedbackRoute
  PublicGpsRoute: typeof PublicGpsRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMapRoute: typeof PublicMapRoute
  PublicOfflineRoute: typeof PublicOfflineRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFeedbackRoute: PublicFeedbackRoute,
  PublicGpsRoute: PublicGpsRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMapRoute: PublicMapRoute,
  PublicOfflineRoute: PublicOfflineRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminApiRoute: typeof AdminApiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBoundariesRoute: typeof AdminBoundariesRoute
  AdminPilotRoute: typeof AdminPilotRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiRoute: AdminApiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBoundariesRoute: AdminBoundariesRoute,
  AdminPilotRoute: AdminPilotRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
